apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
  namespace: cloud-namespace
spec:
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
